openapi: 3.2.0
info:
  version: v1
  title: Listrak Email REST Content Folder API
  description: '# Introduction

    Welcome to the Listrak Email REST API!'
  x-logo:
    url: /Email/Resources/Images/Logo.png
servers:
- url: https://api.listrak.com/email
tags:
- name: ContentFolder
  description: The Content Folder resource allows you to retrieve the folder hierarchy of the content library for a list.
paths:
  /v1/ContentFolder:
    get:
      tags:
      - ContentFolder
      summary: Get all Content Folders
      description: Returns the collection of content library folders associated with the account.
      operationId: ContentFolder_GetContentFolderCollection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection_ContentFolder'
              example:
                status: 200
                data:
                - contentFolderId: 0
                  listId: null
                  parentFolderId: null
                  folderName: null
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 400
                error: ERROR_INVALID_PARAMETER
                message: An invalid value was supplied for {Parameter}.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 401
                error: ERROR_UNAUTHORIZED
                message: Authorization was denied for this request.
      security:
      - OAuth 2:
        - Message
      x-code-samples:
      - lang: C#
        source: 'var client = new HttpClient();


          client.BaseAddress = new Uri("https://api.listrak.com/email/");

          client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);


          var response = await client.GetAsync("v1/ContentFolder");

          '
      - lang: PHP
        source: "$client = new \\GuzzleHttp\\Client([\n\t'base_uri' => 'https://api.listrak.com/email/'\n]);\n\n$res = $client->request('GET', 'v1/ContentFolder',  [\n\t'headers' => ['Authorization' => 'Bearer ' . $accessToken]\n]);\n"
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          format: int32
          description: HTTP status code.
          type: integer
        error:
          description: Error code indicating what error has occured.
          type: string
        message:
          description: Message describing the status and the error that occurred.
          type: string
    Collection_ContentFolder:
      type: object
      properties:
        status:
          format: int32
          description: HTTP status code.
          type: integer
        data:
          description: Collection of return data from the given call.
          type: array
          items:
            $ref: '#/components/schemas/ContentFolder'
    ContentFolder:
      description: A content library folder resource.
      type: object
      properties:
        contentFolderId:
          format: int32
          description: Identifier used to locate the content folder.
          type: integer
        listId:
          format: int32
          description: Identifier of the list this folder belongs to. Null indicates a company-level folder.
          type: integer
        parentFolderId:
          format: int32
          description: Identifier of the parent folder. Null indicates the root folder.
          type: integer
        folderName:
          description: Name of the content folder.
          type: string
x-tagGroups:
- name: API Reference
  tags:
  - Campaign
  - Contact
  - ContactSegmentationField
  - Content
  - ContentFolder
  - Conversation
  - ConversationMessage
  - ConversationMessageActivity
  - ConversationMessageLink
  - ConversationMessageLinkClicker
  - ConversationMessageSummary
  - ConversationSummary
  - Event
  - EventGroup
  - Folder
  - IpPool
  - List
  - ListImport
  - ListImportContact
  - ListImportStatus
  - ListImportSummary
  - Message
  - MessageActivity
  - MessageLink
  - MessageLinkClicker
  - MessageStatus
  - MessageSummary
  - SavedAudience
  - SavedMessage
  - SegmentationField
  - SegmentationFieldGroup
  - SplitTest
  - TransactionalMessage
  - TransactionalMessageActivity
  - TransactionalMessageResend
